//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularMVC.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PorfolioStock
    {
        public int StockId { get; set; }
        public string STOCKNAME { get; set; }
        public string DESCRIPTION { get; set; }
        public int NETPOSITION { get; set; }
        public decimal AVGRATE { get; set; }
        public Nullable<decimal> CLOSING { get; set; }
        public decimal MARKETRATE { get; set; }
        public decimal GAINLOSS { get; set; }
        public decimal MARKETVAL { get; set; }
        public decimal PERCENTCHANGE { get; set; }
        public string ISIN { get; set; }
        public decimal HOLDINGVALUE { get; set; }
    }
}
