//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularMVC.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTransaction
    {
        public int StockTransactionId { get; set; }
        public string STOCKNAME { get; set; }
        public string DESCRIPTION { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string TransactionType { get; set; }
        public decimal Rate { get; set; }
        public decimal Quantity { get; set; }
        public decimal Amount { get; set; }
    }
}
